apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment8deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginxconfig
              mountPath: /etc/nginx/sites-available/
      volumes:
        - name: nginxconfig
          configMap:
            name: assignment8config
