apiVersion: v1
kind: Pod
metadata:
  name: assignment6pod
spec:
  containers:
    - name: container1
      image: busybox
      volumeMounts:
        - name: assignment6vol
          mountPath: /workdir
    - name: container2
      image: busybox
      volumeMounts:
        - name: assignment6vol
          mountPath: /workdir/tmp
  volumes:
    - name: assignment6vol
      emptyDir: {}
