apiVersion: v1
kind: Pod
metadata:
  name: assignment9deployment
spec:
  serviceAccountName: assignment9sa
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      env:
        - name: admin_uname
          valueFrom:
            configMapKeyRef:
              name: assignment9config
              key: username
        - name: admin_password
          valueFrom:
            configMapKeyRef:
              name: assignment9config
              key: password
