apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: assignment11hpa
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: assignment11deployment
    apiVersion: apps/v1
  targetCPUUtilizationPercentage: 60
