apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-details-doc
  labels:
    doc: deployment
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      doc: deployment
  template:
    metadata:
      labels:
        doc: deployment
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: createandcopyfile
          image: busybox
          command:
            - wget
            - "-O"
            - "/workdir/index.html"
            - https://kubernetes.io/docs/concepts/workloads/controllers/deployment
          volumeMounts:
            - name: workdir
              mountPath: /workdir
      volumes:
        - name: workdir
          emptyDir: {}
